# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
[graph]
all-features = true
exclude = [
    # dev only dependency
    "criterion"
]

[advisories]
version = 2
ignore = [
    { id = "RUSTSEC-2024-0368", reason = "We're only using olm-sys for unit tests" },
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]
exceptions = [
    { allow = ["Unicode-3.0"], crate = "unicode-ident" },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

allow-git = [
    "https://github.com/poljar/olm-rs",
    "https://github.com/poljar/olm-sys",
]
