owners = ["poljar", "dkasak"]

pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
pre-release-replacements = [
    {file="README.md", search="vodozemac = .*", replace="{{crate_name}} = \"{{version}}\""},
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
    {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
]

sign-tag = true
tag-message = "Release {{crate_name}} version {{version}}"
tag-name = "{{prefix}}{{version}}"

enable-all-features = true

# Necessary to work with jujutsu
allow-branch = ["HEAD", "release-*"]
