[package]
name = "vodozemac-afl"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
afl = "*"

[dependencies.vodozemac]
path = "../.."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]
