name: CI

on:
  push:
  pull_request:
    branches: [ main ]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Install rust
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      with:
        toolchain: nightly
        components: rustfmt

    - name: Cargo fmt
      run: cargo fmt --all -- --check

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Check the spelling of the files in our repo
      uses: crate-ci/typos@cf5f1c29a8ac336af8568821ec41919923b05a83

  clippy:
    name: Run clippy
    needs: [style]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Install rust
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      with:
        toolchain: nightly
        components: clippy

    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

    - name: Clippy (all-features)
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Clippy (no-default-features)
      run: cargo clippy --all-targets --no-default-features -- -D warnings

  hack:
    name: Check that each feature compiles independently
    needs: [style]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Install Rust
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      with:
        toolchain: stable

    - name: Load cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

    - name: Install cargo-hack
      uses: taiki-e/install-action@85b24a67ef0c632dfefad70b9d5ce8fddb040754
      with:
        tool: cargo-hack

    - name: Check that our features compile
      run: cargo hack check --each-feature --no-dev-deps

  test:
    name: ${{ matrix.target.name }} ${{ matrix.channel }}
    needs: [clippy]

    runs-on: ${{ matrix.target.os }}

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        target: [
          { "os": "ubuntu-latest",  "toolchain": "x86_64-unknown-linux-gnu", "name": "Linux GNU" },
          { "os": "macos-15-intel", "toolchain": "x86_64-apple-darwin ",     "name": "macOS x86" },
          { "os": "macos-latest",   "toolchain": "aarch64-apple-darwin",     "name": "macOS arm" },
          { "os": "windows-latest", "toolchain": "x86_64-pc-windows-msvc",   "name": "Windows MSVC" },
        ]
        channel: [stable, beta, nightly]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: ${{ format('{0}-{1}', matrix.channel, matrix.target.toolchain) }}

      - name: Install nextest
        uses: taiki-e/install-action@85b24a67ef0c632dfefad70b9d5ce8fddb040754
        with:
          tool: nextest

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Test
        run: cargo nextest run --profile ci --all-features

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          use_oidc: true
          report_type: "test_results"
