name: Code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  code_coverage:
    name: Code Coverage
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'push' || !github.event.pull_request.draft

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Install Rust
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      with:
        toolchain: stable

    - name: Load cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

    - name: Install cargo-llvm-cov, nextest, just
      uses: taiki-e/install-action@5f57d6cb7cd20b14a8a27f522884c4bc8a187458
      with:
        tool: cargo-llvm-cov,nextest,just

    - name: Create the coverage report
      run: just coverage-codecov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
      with:
        use_oidc: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
      with:
        use_oidc: true
        report_type: "test_results"
