name: Mutation tests (full)

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    name: cargo-mutants (full)

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5

      - name: Install cargo-mutants
        uses: taiki-e/install-action@a37010ded18ff788be4440302bd6830b1ae50d8b
        with:
          tool: cargo-mutants

      - name: Run mutant tests
        run: cargo mutants -vV --no-shuffle --in-place

      - name: Archive mutants.out
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        if: always()
        with:
          name: mutants-full.out
          path: mutants.out
