name: Mutation tests (full)

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    name: cargo-mutants (full)

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4

      - name: Install cargo-mutants
        uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419
        with:
          tool: cargo-mutants

      - name: Run mutant tests
        run: cargo mutants -vV --no-shuffle --in-place

      - name: Archive mutants.out
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: always()
        with:
          name: mutants-full.out
          path: mutants.out
